/* Copyright (c) 2017, Daniel Mensinger
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *     * Redistributions of source code must retain the above copyright
 *       notice, this list of conditions and the following disclaimer.
 *     * Redistributions in binary form must reproduce the above copyright
 *       notice, this list of conditions and the following disclaimer in the
 *       documentation and/or other materials provided with the distribution.
 *     * Neither the name of the Daniel Mensinger nor the
 *       names of its contributors may be used to endorse or promote products
 *       derived from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
 * ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
 * WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 * DISCLAIMED. IN NO EVENT SHALL Daniel Mensinger BE LIABLE FOR ANY
 * DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 * (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
 * ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
 * SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */
/*!
 * \file defines.hpp
 * \note This file is automatically generated.
 * Please edit only defines.in.hpp in the folder "PROJECT_ROOT/cmake/templates/"
 */

#pragma once

#include <stdint.h>

#define USE_GLIBC     @CM_UNIX_GLIBC@
#define USE_LIBUNWIND @CM_UNIX_LIBUNWIND@
#define USE_WINDOWS   @CM_WIN32_WINDOWS@

#define USE_DWFL      @CM_UNIX_LIBDWLF@
#define USE_BFD       @CM_UNIX_LIBBFD@
#define USE_FALLBACK  @CM_UNIX_EXTERNALFALLBACK@

#define VERBOSE_DEBUG @CM_VERBOSE_DEBUG@

#if !USE_GLIBC && !USE_LIBUNWIND && !USE_WINDOWS
#error "No Backend (tracer engine) enabled"
#endif

#if !USE_DWFL && !USE_BFD && !USE_WINDOWS && !USE_FALLBACK
#error "No Backend (debugging engine) enabled"
#endif

#if _WIN32
#include <Windows.h>
#endif

#define DISABLE_STD_FILESYSTEM @CM_DISABLE_FILESYSTEM@

namespace tracer {

#if UINTPTR_MAX == 0xffffffff            // 32-bit
typedef uint32_t Address;
#elif UINTPTR_MAX == 0xffffffffffffffff  // 64-bit
typedef uint64_t Address;
#else                                    // wtf
#error "Could not detect address legth"
#endif

namespace constants {

const unsigned int MAX_FUNC_NAME   = 128;
const unsigned int MAX_TRACE_DEPTH = 512;

const int         VERSION_MAJOR     = @CM_VERSION_MAJOR@;
const int         VERSION_MINOR     = @CM_VERSION_MINOR@;
const int         VERSION_PATCH     = @CM_VERSION_PATCH@;
const int         GIT_LAST_TAG_DIFF = @CM_TAG_DIFF@;
const char *const VERSION_GIT       = "@CM_VERSION_GIT@";
const char *const INSTALL_PREFIX    = "@CMAKE_INSTALL_PREFIX@";
}
}
